id: P009469
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG25320
  title: རྟ་ནག་རྣམ་འགྲེལ།
  author: ''
  volumes:
    aaa8c141292e4e88a4483e0ffb3a46a8:
      image_group_id: I1KG25322
      title: ''
      volume_number: 1
      total_pages: 446
    f7076ede8fbc4ce7ae5eba660d6c09e5:
      image_group_id: I1KG25323
      title: ''
      volume_number: 2
      total_pages: 704
