id: I70E7A74C
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T14:22:11+00:00'
last_modified: '2022-06-08T11:15:51.742248+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG25320
  title: རྟ་ནག་རྣམ་འགྲེལ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    F07E:
      image_group_id: I1KG25322
      title: ''
      total_pages: 446
      order: 1
      base_file: F07E.txt
    81E2:
      image_group_id: I1KG25323
      title: ''
      total_pages: 704
      order: 2
      base_file: 81E2.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
